a=int(input("Enter the first number :"))
b=int(input("Enter the second number:"))
print("Addition (a+b):",a+b)
print("subtraction (a-b):",a-b)
print("Multiplication (a*b)",a*b)
print("Normal Division (a/b):",a/b)
print("Modules/Remainder (a%b)",a%b)
print("Floor Division (a//b):",a//b)
print("Exponentietion/Power(a**b):",a**b)
